version: "3.8"
services:
  rabbitmq3:
    container_name: rabbitmq
    image: rabbitmq:3.8-management-alpine
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=deokdev
      - RABBITMQ_DEFAULT_PASS=deokdevpassword
    ports:
      - "5672:5672"
      - "15672:15672"

  tracker:
    depends_on:
      - rabbitmq3
    container_name: tracker
    build:
      context: ./tracker_publisher
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./:/app
    environment:
      - MINT_ACCOUNT=${MINT_ACCOUNT}
      - CLUSTER_ENDPOINT=${CLUSTER_ENDPOINT}
      - MQ_HOST=${MQ_HOST}
      - MQ_USER=${MQ_USER}
      - MQ_PASSWORD=${MQ_PASSWORD}
    links:
      - "rabbitmq3:rabbitmq"
  tracker2:
    depends_on:
      - rabbitmq3
    container_name: tracker2
    build:
      context: ./tracker_publisher
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./:/app
    environment:
      - MINT_ACCOUNT=${MINT_ACCOUNT}
      - CLUSTER_ENDPOINT=${CLUSTER_ENDPOINT}
      - MQ_HOST=${MQ_HOST}
      - MQ_USER=${MQ_USER}
      - MQ_PASSWORD=${MQ_PASSWORD}
    links:
      - "rabbitmq3:rabbitmq"
  receiver:
    depends_on:
      - rabbitmq3
    container_name: receiver
    build:
      context: ./tracker_receiver
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./:/app
    environment:
      - MINT_ACCOUNT=${MINT_ACCOUNT}
      - DB_URL=${DB_URL}
      - MQ_HOST=${MQ_HOST}
      - MQ_USER=${MQ_USER}
      - MQ_PASSWORD=${MQ_PASSWORD}
    links:
      - "rabbitmq3:rabbitmq"
