version: "3.8"
services:
  rabbitmq3:
    container_name: rabbitmq
    image: rabbitmq:3.8-management-alpine
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=deokdev
      - RABBITMQ_DEFAULT_PASS=deokdevpassword
    ports:
      - "5672:5672"
      - "15672:15672"

  receiver:
    depends_on:
      - rabbitmq3
    container_name: receiver
    build:
      context: ./account_tracker_mq_receiver
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./:/app
    environment:
      - MINT_ACCOUNT=${MINT_ACCOUNT}
      - DB_URL=${DB_URL}
      - MQ_ENDPOINT=${MQ_ENDPOINT}
    links:
      - "rabbitmq3:rabbitmq"

  tracker:
    depends_on:
      - rabbitmq3
      - receiver
    container_name: tracker
    build:
      context: ./account_tracker_websocket_client
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./:/app
    environment:
      - MINT_ACCOUNT=${MINT_ACCOUNT}
      - CLUSTER_ENDPOINT=${CLUSTER_ENDPOINT}
      - MQ_ENDPOINT=${MQ_ENDPOINT}
    links:
      - "rabbitmq3:rabbitmq"
  tracker2:
    depends_on:
      - rabbitmq3
      - receiver
    container_name: tracker2
    build:
      context: ./account_tracker_websocket_client
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./:/app
    environment:
      - MINT_ACCOUNT=${MINT_ACCOUNT}
      - CLUSTER_ENDPOINT=${CLUSTER_ENDPOINT}
      - MQ_ENDPOINT=${MQ_ENDPOINT}
    links:
      - "rabbitmq3:rabbitmq"
